import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.scss'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: {
		absolute: 'SEO Optimization',
		template: `%s | SEO Optimization`,
	},
	description: 'Generated by create next app',
	icons: {
		icon: '/favicon.svg',
		shortcut: '/favicon.svg',
		apple: '/apple-touch-icon.png',
		other: {
			rel: '/',
			url: '/android-chrome-192x192.png',
			sizes: '192x192',
			type: 'image/png',
		},
	},
	formatDetection: {
		telephone: false,
	},
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>{children}</body>
		</html>
	)
}
